### ISSUE TITLE
Help using, getting error when configuring

### ISSUE THREAD

**Issue by stevenpeh** [LiviusNL/vault-plugin-secrets-ccp#1]
Hi, I've been trying to use this.  Got it mounted, but when I try setting the config, either via the vault client command or using curl, I keep getting errors for the client_cert, client_key and root_ca config arguments.

When I used the raw pem string in a single line as a string parameter, i.e. 

`{... "client_cert": "-------BEGIN...", `

I get the following errors:

`'client_key': source data must be an array or slice, got string
`
If I use it as an array, i.e. 

`{ .. "client_cert": [ "------BEGIN..."] `

I get this error:

`expected type 'string', got unconvertible type '[]interface {}'`

I've also tried the vault command line using file attach, i.e. 

`vault write ... client_cert=@pathToFile `

I get a similar error as the first one above.

Any tips on how to use this?

Was testing this on vault 1.4.2 in dev mode.  Built using golang 1.13.3 on an aws ec2 with ami linux

**Comment by LiviusNL** [comment]
You cannot provide the PEM file as just a single string, every line of the must end with an newline: \n

**Comment by stevenpeh** [comment]
> You cannot provide the PEM file as just a single string, every line of the must end with an newline: \n

Hi thanks for the help.  I've tried this and still getting the error

`'client_cert': source data must be an array or slice, got string`

Tried both the vault command and using curl

Here's the single line pem string
`-----BEGIN CERTIFICATE-----\nMIIDTTCCAjUCFBxllnMwcd6hXq3qQAKWxfym4zqdMA0GCSqGSIb3DQEBCwUAMFQx\nCzAJBgNVBAYTAkFVMQwwCgYDVQQIDANTeWQxDDAKBgNVBAcMA05TVzEMMAoGA1UE\nCgwDTUJMMQwwCgYDVQQLDANjZ20xDTALBgNVBAMMBHNwZWgwHhcNMjAwNjI0MDcw\nMDI4WhcNMjExMTA2MDcwMDI4WjByMQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29t\nZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMQ0wCwYD\nVQQDDAR0ZXN0MRwwGgYJKoZIhvcNAQkBFg10ZXN0QHRlc3QuY29tMIIBIjANBgkq\nhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu6sXBxq2/GMUE+aeFmCUYITJH0TQmmfi\ntQhq+B/I5DRjUzUhXV/bdIn363E6EFiGp0Xq68PpfImjX3+XNolYPPwwt3TClJY8\nr9ef365d7QXdEFjPDaOV+kzFbo2muR/+hnHx4NJoeIyYt+TQFO/Mk25BmAMkeO0S\nQ59j23niXOao7eji9/5bmLHANoh2w+K2+9QNgQEYsEq+yk94FZ1fOznG9UDjJd61\n+zCT2x3SHrc+GktfE/28fiAVW/nIiFMF2Qf9A8VcTugarTazjEiAhd98MGjiZsxu\nKLboL7GemX3xUpLZuOQxRKdg+5YEmMKKeTk8N+OcEDgyVJBNsZW45QIDAQABMA0G\nCSqGSIb3DQEBCwUAA4IBAQBoRPpBEJa6/O1UxbxMJMLvzbDefRyIyH4Ajnp2AlSj\nlJphakEDfddhFWRp1O8csNtwOqVnOarv/4X9lwgmfGWuT/UqnLawOp9mFoMiNajP\niP4rtKlbQI+HILdkrqNBk7h7xHpQS+fLoOpwMz3CSTdFghK7QyFOlg6In3y6jsWW\nvwRkCM9sP+PlTIglSKRroA5tZ110Wv6bPB7hoAht1Nthf9GjxdPAXbWu92VH512w\nyjqIK8qmg/OEpuU6xjUHsp8cANEyByMcNqb6CXS/pq+kI1WvCEwNV0lJKwnmzSwc\nyXY0Va6zw4utie2CpPI/CJfWOhobch9O0Ly16ujDU2Sj\n-----END CERTIFICATE-----\n`

If you can try it on your end would be good.

Here's the different commands I ran:

`./vault write ccp/config host=xxxx application_id=xxxx client_cert=@cm.pem`
`./vault write ccp/config host=xxxx application_id=xxxx client_cert="pem string above"`

via curl:
`curl --no-proxy "*" -H "X-Vault-Token: s.0LqsU9ktz7G50DrS2uU5V1Zd" --data @config.json -X POST "http://localhost:8200/v1/ccp/config"`

where config.json is
`{
   "host": "xxxx",
   "application_id": "xxxx",
   "client_cert": "pem string above"
}`

Any other tips?

**Comment by stevenpeh** [comment]
Any help on this?
